name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - name: Check
        run: moon check --deny-warn
      - name: Format
        run: moon fmt --check
      - name: Test
        run: moon test --deny-warn
      - name: Install xz-utils
        run: sudo apt-get update && sudo apt-get install -y xz-utils
      - name: Encode differential
        run: python3 scripts/diff_encode.py
